name: browser-home-page
 
on:
  push:
    branches: 
      - main
 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
  
#关键配置
    steps:
      - uses: actions/checkout@v2
      - name: pnpm install
        run: pnpm install
      - name: pnpm run build
        run: pnpm run build
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
            source: 'dist/*'
    # SSH address  服务器地址
            host: ${{ secrets.REMOTE_HOST }}
    # Remote dir path  服务器下部署文件存放路径
            target: ${{ secrets.REMOTE_PATH }}
    # SSH Port  服务器端口
            port: 22
    # SSH User name   用户名
            username: ${{ secrets.USER_NAME }}
    # SSH User password  用户密码
          #  password: ${{ secrets.PASSWORD }}
    # key  密匙
            key: ${{ secrets.SSH_KEY }}
